<?php
/**
 * Plugin Name:       KloudStack Observability for Azure
 * Plugin URI:        https://kloudstack.com/plugins/azure-observability/
 * Description:       Sends WordPress request, exception and browser telemetry to Azure Application Insights. Built for WordPress running on Azure.
 * Version:           2.0.0-dev
 * Requires at least: 6.0
 * Requires PHP:      7.4
 * Author:            KloudStack
 * Author URI:        https://kloudstack.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       kloudstack-azure-observability
 * Domain Path:       /languages
 *
 * @package KloudStack\Observability
 */

declare(strict_types=1);

namespace KloudStack\Observability;

defined('ABSPATH') || exit;

const VERSION        = '2.0.0-dev';
const SCHEMA_VERSION = 1;
const SLUG           = 'kloudstack-azure-observability';
const PREFIX         = 'kloudstack_obs_';

define('KloudStack\\Observability\\PLUGIN_FILE', __FILE__);
define('KloudStack\\Observability\\PLUGIN_DIR', plugin_dir_path(__FILE__));
define('KloudStack\\Observability\\PLUGIN_URL', plugin_dir_url(__FILE__));

/**
 * Minimum platform check.
 *
 * Runs before anything else loads. A plugin whose job is to observe a site must never be the
 * reason the site fails, so an unsupported platform degrades to an admin notice rather than a
 * fatal error.
 */
if (version_compare(PHP_VERSION, '7.4', '<')) {
    add_action('admin_notices', static function (): void {
        printf(
            '<div class="notice notice-error"><p>%s</p></div>',
            esc_html(
                sprintf(
                    /* translators: %s: current PHP version */
                    __(
                        'KloudStack Observability for Azure requires PHP 7.4 or later. This site is running PHP %s. The plugin is inactive.',
                        'kloudstack-azure-observability'
                    ),
                    PHP_VERSION
                )
            )
        );
    });

    return;
}

/**
 * PSR-4 autoloader scoped to this plugin's namespace.
 *
 * Deliberately hand-written rather than generated by Composer: WordPress plugins share a single
 * PHP process, and shipping a Composer autoloader is a well-known source of conflicts when two
 * plugins vendor different versions of the same library. This plugin vendors nothing.
 */
spl_autoload_register(static function (string $class): void {
    $prefix = __NAMESPACE__ . '\\';
    $length = strlen($prefix);

    if (strncmp($prefix, $class, $length) !== 0) {
        return;
    }

    $relative = substr($class, $length);
    $path     = PLUGIN_DIR . 'src/' . str_replace('\\', '/', $relative) . '.php';

    if (is_readable($path)) {
        require_once $path;
    }
});

/**
 * Plugin instance accessor.
 *
 * The only global function this plugin defines. Everything else is namespaced.
 */
function kloudstack_obs(): Plugin
{
    static $instance = null;

    if ($instance === null) {
        $instance = new Plugin();
    }

    return $instance;
}

/**
 * Boot.
 *
 * `plugins_loaded` in standard mode. In MU mode the loader calls boot() directly at MU priority
 * so fatals raised while regular plugins load are still captured — see the functional
 * specification, section 5.3.
 */
if (!defined('KLOUDSTACK_OBS_DEFER_BOOT')) {
    add_action('plugins_loaded', static function (): void {
        kloudstack_obs()->boot();
    }, 0);
}